"""Correção na tabela itens_pedido

Revision ID: 4ecfa1a27f39
Revises: 3d8d10d692ac
Create Date: 2025-08-04 09:02:05.830561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecfa1a27f39'
down_revision: Union[str, Sequence[str], None] = '3d8d10d692ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('pedido', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itens_pedido', 'pedidos', ['pedido'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.drop_column('itens_pedido', 'pedido')
    # ### end Alembic commands ###
